FROM nginx

# 複製 nginx.conf 到 Nginx 設定目錄
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 複製 BundleDefinition.html 到 Nginx 網站根目錄，並命名為 index.html
COPY BundleDefinition.html /usr/share/nginx/html/index.html
#COPY ssl.csr /etc/nginx/ssl.csr
#COPY ssl.key /etc/nginx/ssl.key
#EXPOSE 80
#EXPOSE 443